# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-05-15 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotifyDictEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EDEKey', models.CharField(db_index=True, max_length=240)),
                ('EDEValue', models.CharField(db_index=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='EmotifyDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EDName', models.CharField(default='NULL', max_length=50)),
                ('EDType', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmotifyElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EEHappy', models.IntegerField(default=0)),
                ('EESad', models.IntegerField(default=0)),
                ('EESurprise', models.IntegerField(default=0)),
                ('EEAnger', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmotifyLocationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ELLLocation1', models.CharField(max_length=50)),
                ('ELLLocation2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmotifyTimeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETLMonth', models.IntegerField(default=0)),
                ('ETLDay', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='emotifyelement',
            name='EEDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.EmotifyTimeList'),
        ),
        migrations.AddField(
            model_name='emotifyelement',
            name='EELocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.EmotifyLocationList'),
        ),
        migrations.AddField(
            model_name='emotifydictionary',
            name='EDElement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.EmotifyElement'),
        ),
        migrations.AddField(
            model_name='emotifydictentry',
            name='EDEContainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.EmotifyDictionary'),
        ),
    ]
