# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-05-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotifydictentry',
            name='EDEValue',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
