# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-05-21 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_auto_20180516_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotifyTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETText', models.CharField(db_index=True, max_length=300)),
                ('ETContainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.EmotifyDictEntry')),
            ],
        ),
    ]
