# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-05-25 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_auto_20180525_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotifytweet',
            name='ETType',
            field=models.IntegerField(default=0),
        ),
    ]
