# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-05-25 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0005_emotifytweet_ettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotifytweet',
            name='ETKey',
            field=models.CharField(db_index=True, default='', max_length=240),
        ),
    ]
