# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-05-26 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0006_emotifytweet_etkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngerEmotifyTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETKey', models.CharField(db_index=True, default='', max_length=240)),
                ('ETText', models.CharField(db_index=True, max_length=300)),
                ('ETContainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.EmotifyLocationList')),
            ],
        ),
        migrations.CreateModel(
            name='HappyEmotifyTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETKey', models.CharField(db_index=True, default='', max_length=240)),
                ('ETText', models.CharField(db_index=True, max_length=300)),
                ('ETContainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.EmotifyLocationList')),
            ],
        ),
        migrations.CreateModel(
            name='SadEmotifyTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETKey', models.CharField(db_index=True, default='', max_length=240)),
                ('ETText', models.CharField(db_index=True, max_length=300)),
                ('ETContainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.EmotifyLocationList')),
            ],
        ),
        migrations.CreateModel(
            name='SurpriseEmotifyTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETKey', models.CharField(db_index=True, default='', max_length=240)),
                ('ETText', models.CharField(db_index=True, max_length=300)),
                ('ETContainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.EmotifyLocationList')),
            ],
        ),
        migrations.RemoveField(
            model_name='emotifytweet',
            name='ETContainer',
        ),
        migrations.DeleteModel(
            name='EmotifyTweet',
        ),
    ]
